### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by zeeb00** [dhruv-goyal-10/Linkedin-Clone-backend#7]
Can you please share the .env file?

**Comment by dhruv-goyal-10** [comment]
For the .env file, I can share with you the structure of the .env file but not the credentials for obvious reasons.

**Comment by zeeb00** [comment]
That would be great. Just the structure without your credentials.

**Comment by dhruv-goyal-10** [comment]
Sure, here is the structure
`SECRET_KEY=
DATABASE_NAME=
DATABASE_USER=
DATABASE_PASSWORD=
DATABASE_PORT=
DATABASE_HOST=
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
EMAIL_HOST_USER=
EMAIL_HOST_PASSWORD=
ACCOUNT_SID=
AUTH_TOKEN=
MESSAGING_SERVICE_SID=
CLOUDINARY_CLOUD_NAME=
CLOUDINARY_API_KEY=
CLOUDINARY_API_SECRET=
`

**Comment by zeeb00** [comment]
Thank you!
