### ISSUE TITLE
template

### ISSUE THREAD

**Issue by zeeb00** [dhruv-goyal-10/Linkedin-Clone-backend#8]
Can you please share all the templates?

**Comment by dhruv-goyal-10** [comment]
Can you specify about which templates are you exactly talking about?

**Comment by zeeb00** [comment]
The templates that contains html and css scripts for home page/feed, messages, setting page and etc.

**Comment by dhruv-goyal-10** [comment]
Actually, this was a team project and this is just the backend part of the project.
For frontend part refer to this repository [ConnectPlus Frontend](https://github.com/Archiehere/ConnectPlus)

**Comment by zeeb00** [comment]
Awesome, thank you!
